### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by Shou1204** [Shou1204/protospace-38827#5]
# URL
https://protospace-38827.onrender.com/
確認お願いします！

**Comment by motomuun** [comment]
@Shou1204 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
